--- #YAML:1.0
name: POE-Component-StackedProcessor
version: 0.01
author:
  - Daisuke Maki <daisuke@cpan.org>
abstract: Stack Processors In POE
license: perl
requires:
  Class::Data::Inheritable: 0
  POE: 0
  Params::Validate: 0
build_requires:
  Test::More: 0
provides:
  POE::Component::StackedProcessor:
    file: lib/POE/Component/StackedProcessor.pm
    version: 0.01
generated_by: Module::Build version 0.2602
